openapi: 3.0.1
info:
  title: Presidio Todos Test API with No Auth
  version: 1.0.0
servers:
  - url: https://todo-app-no-auth.onrender.com
    description: Development server
paths:
  /todos:
    get:
      summary: Get all todos
      operationId: getTodos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      summary: Create multiple todos
      operationId: createTodos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                todos:
                  type: array
                  items:
                    $ref: "#/components/schemas/Todo"
      responses:
        "201":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    delete:
      summary: Delete Todos accepts an ID to delete
      operationId: deleteTodos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/deleteTodoRequest"
              
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    
components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string

    deleteTodoRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: array
          items:
            type: integer
            format: int64
            description: index of the todo to delete, index can be obtained by getTodos function
            